/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./UserManagement.module.css";

function SearchBar() {
  return (
    <form className={styles.searchBar}>
      <label htmlFor="searchInput" className={styles["visually-hidden"]}>
        Search users
      </label>
      <input
        type="text"
        id="searchInput"
        placeholder="Search here..."
        aria-label="Search users" style={{width:'100%',border:0, 
          outline: 'none',}}
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/dffbbd621a3f481784a0940a3254d4979d054a14506371a26c76ccd097c4da8a?placeholderIfAbsent=true&apiKey=62fcf10bee394026978be26d3a6bac3b"
        className={styles.searchIcon}
        alt=""
      />
    </form>
  );
}

export default SearchBar;
