/**
 * This code was generated by Builder.io.
 */
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import UserTable from "./UserTable";

describe("UserTable", () => {
  it("renders the table headers", () => {
    render(<UserTable />);
    expect(screen.getByText("Actions")).toBeInTheDocument();
    expect(screen.getByText("Name")).toBeInTheDocument();
    expect(screen.getByText("Email Id")).toBeInTheDocument();
    expect(screen.getByText("Phone Number")).toBeInTheDocument();
    expect(screen.getByText("Team")).toBeInTheDocument();
  });

  it("renders user data", () => {
    render(<UserTable />);
    expect(screen.getByText("Project Manager")).toBeInTheDocument();
    expect(screen.getByText("dravendrav213@gmail.com")).toBeInTheDocument();
    expect(screen.getByText("9123456787")).toBeInTheDocument();
    expect(screen.getByText("Management")).toBeInTheDocument();
  });

  it("renders the edit button", () => {
    render(<UserTable />);
    expect(screen.getByText("Edit")).toBeInTheDocument();
  });
});
