/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ProfileCard.module.css";
import personI from "./Personal.png"
import mail from "./mail.png"
import password from "./password.png"
import { Link } from 'react-router-dom';

const ProfileCard = () => {
  return (
    <section className={styles.profileCard}>
      <div className={styles.cardContainer}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/10bcdc0a1ed7e1012ab2c9bb2303c220023d8be3b027a61d975243a9999a36ef?placeholderIfAbsent=true&apiKey=f158a1f6464b4ffba2f9a1dad0c7135d"
          className={styles.profileImage}
          alt="Profile"
        />
        <div className={styles.infoContainer}>
          <div className={styles.blueBox}>
            <div className={styles.boxesContainer}>
            <Link to="/Profile">
                <div className={styles.grayBox}><img src={personI} className={styles.logo}></img><h5 style={{marginTop:'10%',fontSize:'15px',}}>Personal</h5></div>
              </Link>
              <Link to="/Profile/Email">
                <div className={styles.grayBox}><img src={mail} className={styles.logo}></img><h5 style={{marginTop:'10%',fontSize:'15px',}}>Email</h5></div>
              </Link>
              <Link to="/Profile/Password">                
                <div className={styles.grayBox} style={{borderBottom:'4px solid white'}}><img src={password} className={styles.logo} style={{width:'20%',height:'40%'}}></img><h5 style={{marginTop:'10%',fontSize:'15px',}}>Password</h5></div>
              </Link>
            </div>
          </div>
          <div className="mb-3 mt-3" style={{width: '98%'}}>
            <label for="" className="form-label fs-8 fw-semibold">Current Password</label>
            <input type="password" className="form-control" style={{ borderBottom: '2px solid #000', borderRadius: '0', borderTop: 'none', borderLeft: 'none', borderRight: 'none',fontSize:'15px' }} />
          </div>
          <div className="mb-3" style={{width: '98%'}}>
            <label for="" className="form-label fs-8 fw-semibold">New Password</label>
            <input type="password" className="form-control" style={{ borderBottom: '2px solid #000', borderRadius: '0', borderTop: 'none', borderLeft: 'none', borderRight: 'none',fontSize:'15px'}} />
          </div>
          <div className="mb-3" style={{width: '98%'}}>
            <label for="" className="form-label fs-8 fw-semibold">Confirm Password</label>
            <input type="password" className="form-control" style={{ borderBottom: '2px solid #000', borderRadius: '0', borderTop: 'none', borderLeft: 'none', borderRight: 'none',fontSize:'15px' }} />
          </div>
        </div>
        <button className={styles.saveButton}>
          <div className={styles.buttonContent}>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/207243a4f52d752f9770c8c2bb9ded9b7031b636279717a4fd564616ee451886?placeholderIfAbsent=true&apiKey=f158a1f6464b4ffba2f9a1dad0c7135d"
              className={styles.buttonIcon}
              alt=""
            />
            <span className={styles.buttonText}>Save</span>
          </div>
        </button>
      </div>
    </section>
  );
};

export default ProfileCard;
